import { m } from "framer-motion";

export const songs = [
  {
    id: 1,
    text: [
      "In New York I Milly Rock (Rock)",
      "Hide it in my sock (Sock)",
      "Runnin' from an opp (Opp)",
      "And I shoot at opp (Opp), uh, uh (What?)",
    ],
    artist: "Playboi Carti",
    song: "Magnolia",
  },
  {
    id: 2,
    text: [
      "Put 'em in a coffin, put 'em in a coffin",
      "Put 'em in a, uh, put 'em in a, uh, put 'em in a coffin",
      "I jump out the Lamb' truck, she thought that I lost it",
      "I jump off my red eye, push out, then I go to Boston",
    ],
    artist: "Playboi Carti",
    song: "H00DBYAIR",
  },
  {
    id: 3,
    text: [
      "I got a Draco in my bookbag, lil' bitch (Go, yeah, woo)",
      "That motherfucker got a kickback on it (Yeah, woo)",
      "That motherfucker got a kickback on it (Yeah, woo)",
      "And I put this on Onyx, I'ma leave my opp in the cement",
    ],
    artist: "Playboi Carti",
    song: "On That Time",
  },
  {
    id: 4,
    text: [
      "That bag loaded, yeah, got it all the time (Yeah, what?)",
      "Nickelodeon, way I got that slime (Yeah, slime)",
      "The Dream Mode, yeah, tats showin', my teams (What?)",
      "Keep it tucked like a T-shirt, I need that nine",
    ],
    artist: "Playboi Carti",
    song: "Lean 4 Real",
  },
  {
    id: 5,
    text: [
      "I guess you're not feelin' me, uh (What?)",
      "Not feelin' the energy",
      "Baby girl, we can do plan A (Is you mad or what?)",
      "Baby girl, we can do plan B (Bleh)",
    ],
    artist: "Playboi Carti",
    song: "Flex",
  },
  {
    id: 6,
    text: [
      "My emo bitch like to slit her wrists, yeah, she's so dark",
      "She was moving too fast, I had to put that bitch in park",
      "She said Boy, don't start with me, but I already started",
      "How you let your ex drive you crazy, and he ain't got no car?",
    ],
    artist: "Ken Carson",
    song: "Succubus",
  },
  {
    id: 7,
    text: [
      "Like oxygen, without you, baby girl, I can't breathe",
      "I been showin' off my pain lately, I tatted up my sleeve, yeah",
      "Balenciaga my jeans, yeah",
      "Rick Owens still on my tee, yeah",
    ],
    artist: "Ken Carson",
    song: "i need u",
  },
  {
    id: 8,
    text: [
      "London, Paris, Amsterdam, yeah, I'm overseas",
      "She gon' suck my soul out me, yeah, she on her knees",
      "Inhale, exhale, yeah, breathe",
      "12 ask me, What's that smell? Yeah, weed",
    ],
    artist: "Ken Carson",
    song: "overseas",
  },
  {
    id: 9,
    text: [
      "Yeah, ayy, fuck 12",
      "I got too much money, I'm bailin' out, I ain't goin' to jail",
      "If I see the police and they make a right, I make a left",
      "Only opps I got is police 'cause all these niggas be scary as hell",
    ],
    artist: "Ken Carson",
    song: "Fuk 12",
  },
  {
    id: 10,
    text: [
      "I'm trippin', I'm trippin'",
      "I'm trippin', I'm trippin'",
      "This A-C-I-D got me trippin'",
      "It feel like I'm in another dimension",
    ],
    artist: "Ken Carson",
    song: "Rock N Roll",
  },
  {
    id: 11,
    text: [
      "I get bitches, I don't need no wingman (No wingman)",
      "I get richer, I don't sell no weed, man (Not right now)",
      "I smoke dope by the pound, yeah, for real",
      "Huh, I'm on the top of the mountain, king of the hill (We top floor)",
    ],
    artist: "Destroy Lonely",
    song: "if looks could kill",
  },
  {
    id: 12,
    text: [
      "She don't wanna talk, she just tryna vacate (Vacate)",
      "I got a nice place, 'bout to fly her to the A",
      "I got a gangsta ho tryna swing my Drac'",
      "I'm pourin' up eights, ridin' with Lil 8 (Lil 8)",
    ],
    artist: "Destroy Lonely",
    song: "LUV 4 YA",
  },
  {
    id: 13,
    text: [
      "Yeah, I look like a supermodel, and all my draws is Calvin Klein",
      "Yeah, my baby, she built like a bottle, and I'm finna take a sip right now",
      "Yeah, I'm pourin' some lines out the bottle, and I'm finna take a sip right now",
      "Yeah, and I probably won't see you tomorrow 'cause I'm finna take a trip right now",
    ],
    artist: "Destroy Lonely",
    song: "how u feel?",
  },
  {
    id: 14,
    text: [
      "All this dope burnin' on my skin (Woah, burnin' on my skin)",
      "All this drank that I been sippin', I need codeine (Woah, sippin', I need codeine)",
      "I just slayed another freak and she don't know me (Woah, she don't know me)",
      "All this money been replacin' my friends (Woah, replacin' my friends)",
    ],
    artist: "Destroy Lonely",
    song: "moment of silence",
  },
  {
    id: 15,
    text: [
      "Racks, they come in the mail",
      "Yeah, bags, they going for sale",
      "Yeah, and thе shit that I rock YSL",
      "Yeah, and your ship is gon' sink, it won't sail",
    ],
    artist: "Destroy Lonely",
    song: "Oh Yeah",
  },
  {
    id: 16,
    text: [
      "Nigga get put in a blunt",
      "Ha, swingin' and fightin' for nothin'",
      "Hit that boy with a whole hundred, ARP get it done",
      "Step on that boy, it ain't nothin'",
    ],
    artist: "Homixide Gang",
    song: "R50",
  },
  {
    id: 17,
    text: [
      "Yeah, we got Pakistan sticks, shoot missiles",
      "I popped me a X, I got meds in my system",
      "Might call up Meech', the big hits, get lit",
      "My brothers love spinnin'",
    ],
    artist: "Homixide Gang",
    song: "Lifestyle",
  },
  {
    id: 18,
    text: [
      "I'ma see how that Draco work (What?)",
      "I'ma see how that Draco twerk (What?)",
      "Talk on my name, you gon' get your ass hurt",
      "We slidin', big B’s, thought it was a vert",
    ],
    artist: "Homixide Gang",
    song: "Uzi Work",
  },
  {
    id: 19,
    text: [
      "Keep switch on all of my pistols (Nigga, tweak out)",
      "Mixin' my cup in my system (System)",
      "I get the head and dismiss her (Dismiss her)",
      "All of my kids on her face (On her face)",
    ],
    artist: "Homixide Gang",
    song: "ADHD",
  },
  {
    id: 20,
    text: [
      "Double D titties sittin' on thе AR",
      "He rappin' on Wax, wasn't even in the car",
      "Hit the plug from the bay, he know what we want",
      "These niggas two-faced, be snakes, be clones",
    ],
    artist: "Homixide Gang",
    song: "Snotty Wax!",
  },
  {
    id: 21,
    text: [
      "She ride the dick like a carnival",
      "Bend her over, havin' flashbacks, she gon' eat me up like a carnivore",
      "It's the way I pop my shit, the hoes not ready, I'm goin' barnacles",
      "Movin', I feel like I'm Jason, can't get arrested, I make 'em stumble",
    ],
    artist: "Playboi Carti",
    song: "Carnival",
  },
  {
    id: 22,
    text: [
      "Uh, woke up with my toolie, what it do? Huh, uh",
      "Meet me in the alley with the troops, uh",
      "I got red shooters, I got blue, huh, yeah",
      "Let that thing down and point at you, huh, uh",
    ],
    artist: "Playboi Carti",
    song: "Shoota",
  },
  {
    id: 23,
    text: [
      "I was brought up different, uh (Let's go)",
      "So my vision different, uh (Let's go)",
      "Yeah, my bitches different, uh (I was brought up different)",
      "Ridin' 'round in tinted, uh (So my vision different)",
    ],
    artist: "Playboi Carti",
    song: "Had 2",
  },
  {
    id: 24,
    text: [
      "Schyeah, holding that beam, let's go (Schyeah)",
      "No self-esteem, she low (Schyeah)",
      "Talk about money, control (Schyeah)",
      "I just be losin' my mind, yeah (Schyeah)",
    ],
    artist: "Playboi Carti",
    song: "Menage",
  },
  {
    id: 25,
    text: [
      "Let the real speak, uh, let the fake get gone",
      "Let the fake go home, tell 'em niggas go, leave my ass alone",
      "I been on my own, I been all alone",
      "I fell on my face, I got up my own",
    ],
    artist: "Playboi Carti",
    song: "24 Songs",
  },
  {
    id: 26,
    text: [
      "Yeah, its Opium, lil' bitch, I'm stamped",
      "Got that shit tatted next to my ear",
      "I ain't drop no music in a year",
      "I'm still shittin' on your whole career",
    ],
    artist: "Ken Carson",
    song: "Veteran",
  },
  {
    id: 27,
    text: [
      "Yeah, we all DTF, yeah, we all down to fuck some hoes",
      "She say she down to do the drugs I do, and now she movin' slow",
      "I'm off the shrooms, I'm off the codeine, woah, woah, woah",
      "Don't walk up on me like you know me, nigga, I'ma blow",
    ],
    artist: "Ken Carson",
    song: "free young thug",
  },
  {
    id: 28,
    text: [
      "Stealin' my swag, yeah, I'm your dad, bitch",
      "Fuck on your bitch, yeah, she call me daddy",
      "Look at my jeans, Balenci' I'm sagging",
      "I came from the future, you came from the past",
    ],
    artist: "Ken Carson",
    song: "higher & flyer",
  },
  {
    id: 29,
    text: [
      "These niggas green like Ben 10 (Oh yeah)",
      "So they can't stand next to me (Oh nah)",
      "Pull up with an FN",
      "Spinned the block, all you heard was a screech",
    ],
    artist: "Ken Carson",
    song: "Teen X",
  },
  {
    id: 30,
    text: [
      "This that murder music",
      "I let that chopper sing and they listen to it",
      "My bitch, she like to get high, yeah, we gettin' booted",
      "I pop a Perc' and sip my drank, yeah, now I'm zooted",
    ],
    artist: "Ken Carson",
    song: "Murda Musik",
  },
  {
    id: 31,
    text: [
      "I'm the blond hair don, lil' bitch, I ain't playin'",
      "Yeah, I'm the boss, what the fuck is they sayin'?",
      "Nigga wanna play, leave him right where he standin'",
      "And this bitch so bad, let her hold my hand",
    ],
    artist: "Destroy Lonely",
    song: "​hldmyhnd.wav",
  },
  {
    id: 32,
    text: [
      "Yeah, I put that ho on the X, now she piped up, she getting piped down",
      "I put that ho on that Oxy' and codeine, now that ho geeked up",
      "Yeah, I'm on some Oxy' and motherfuckin' codeine, lil' bitch, I'm geeked out",
      "Yeah, Balenciaga boots so big, these niggas get stomped out",
    ],
    artist: "Destroy Lonely",
    song: "FAKENGGAS",
  },
  {
    id: 33,
    text: [
      "Uh, Shawty tryna get in my mind, yeah, she ask me what I think",
      "Yeah, she know that black my favorite color, but her lil' pussy pink",
      "Yeah, I just been countin' up all this paper, give a fuck 'bout what they say",
      "Yeah, I told all my hoes I love 'em and I'm tryna paint they face",
    ],
    artist: "Destroy Lonely",
    song: "OTW",
  },
  {
    id: 34,
    text: [
      "Sippin' on purple mud straight out the bottle (Mud)",
      "Slim-thick bitch, yeah, she built like a model",
      "Codeine got me moving slow but it's full throttle",
      "And I'm blowing through these bands like I just hit the lotto' (Beep)",
    ],
    artist: "Destroy Lonely",
    song: "mud",
  },
  {
    id: 35,
    text: [
      "Givenchy, Versace, bought her Dior, Margiela",
      "Put Chanel on her sweater",
      "She want whatever, whichever",
      "I do whatever whenever",
    ],
    artist: "Destroy Lonely",
    song: "Suicide Mission",
  },
  {
    id: 36,
    text: [
      "I just had lil' 5unna spin that bin, he was tired as fuck (Haha)",
      "I just walked in the club, and I threw a dub, and I had that blicky tucked (Blicky tucked)",
      "Bitch wanna ride in this truck? She got a Glock, and that tommy tucked",
      "Heard they went and zipped him up",
    ],
    artist: "Homixide Gang",
    song: "5unna",
  },
  {
    id: 37,
    text: [
      "We rockin' out shows, I'm catching some plays",
      "Ain't dumpin' out loads, ain't no minimum wage",
      "We been out the law for thirty-one days",
      "You come and you show up, and you getting no wave",
    ],
    artist: "Homixide Gang",
    song: "Big O Shit",
  },
  {
    id: 38,
    text: [
      "Zillion or trillion ridiculous, did that boy ten toes on Dickies",
      "We rock out the show, we handle the business",
      "Tag on him hit 'em, we go and get 'em",
      "Don’t speak on wax if you go on that mission",
    ],
    artist: "Homixide Gang",
    song: "Grab Da Door!",
  },
  {
    id: 39,
    text: [
      "Yeah, turn them bricks for a bag, hah (What?)",
      "Cut it down, nigga, make a slab, hah (What?)",
      "Have you ever seen him with the dope? Ah (Dope)",
      "Have you ever seen that bitch lock? Ah (What?)"
    ],
    artist: "Homixide Gang",
    song: "Block Work",
  },
  {
    id: 40,
    text: [
      "My pocket withdrawal like a biscuit (Like a biscuit)",
      "We stackin' this shit through the ceiling (The ceiling)",
      "They know that we rockin' these diamonds",
      "They know that we handle the business"
    ],
    artist: "Homixide Gang",
    song: "C4N",
  },
];
